### ISSUE TITLE
折线图要能自定义Y轴就好了

### ISSUE THREAD

**Issue by wangyuuuu** [huangshun11/Charts#31]
或者 作者给个曲线救国的方法

**Comment by FelixVarius** [comment]
曲线救国啥意思。

**Comment by wangyuuuu** [comment]
就是 怎么加函数 能实现。或者给个思路 我先搞进去

**Comment by FelixVarius** [comment]
看 Y Axis

**Comment by wangyuuuu** [comment]
就是你现在只能均分y轴 比如说 给个最大100 最小值0  然后设置分割数2 最后是均分的 0 50 100。
但是我需要的是 比如 y轴 显示 5 10 25 80 100  怎么实现 ？
辛苦了

**Comment by FelixVarius** [comment]
这个暂时不支持。
